import os

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
OPENAI_API_VERSION = "2024-04-01-preview"
PSDEV_AZURE_DEVOPS_TOKEN = os.getenv("PSDEV_AZURE_DEVOPS_TOKEN")
PSDEV_AZURE_DEVOPS_ORGANISATION_URL = os.getenv("PSDEV_AZURE_DEVOPS_ORGANISATION_URL")
PSDEV_JIRA_API_TOKEN = os.getenv("PSDEV_JIRA_API_TOKEN")